### ISSUE TITLE
运行结果不成功

### ISSUE THREAD

**Issue by gudaost** [MGMCN/Python3-dlib-#1]
已经修改路径，可以运行，但是：
1、图片并没有移动
2、我在cmd里面运行的，结果出现了从1到1404的数字……

**Comment by gudaost** [comment]
更改路径的部分是：
# 待检测的图片路径
imagepath = "D:\\1\\test in\\"
# 训练好的数据集模型
model_path = 'D:\\1\\shape_predictor_68_face_landmarks.dat'
# 移动到另一个文件夹的路径
moving_path = "D:\\1\\test out\\"

**Comment by MGMCN** [comment]
你好，请先访问https://github.com/MGMCN/python3-ajax-&nbsp;。使用这个代码爬取图片放置到对应文件夹，然后按照你存放的相应路径修改https://github.com/MGMCN/Python3-dlib-的代码。这个代码里面range（1，1400+）的这个数字代表的是我发你的第一个链接爬下来图片重命名的编号，如果你的图片名字不同的话需要你自行修改代码。如果是你自己已有的图片库分类的话，需要你修改逻辑部分代码。识别部分代码不需要修改。谢谢。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: gudaost <notifications@github.com&gt;
发送时间: 2020年6月19日 15:49
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[MGMCN/Python3-dlib-] 运行结果不成功 (#1)





 
已经修改路径，可以运行，但是：
 1、图片并没有移动
 2、我在cmd里面运行的，结果出现了从1到1404的数字……

**Comment by gudaost** [comment]
汗……
没学过python，看起来有些难度啊
先确认一件事情：
如果我只使用筛分，而不使用下载的功能，是否就可以不使用另外一个？然后我修改了与路径有关的内容，就可以正常识别并移动了？

**Comment by MGMCN** [comment]
对的，你的理解是对的，如果你只使用筛选功能，只需要使用筛选部分的代码。同时你的图片名需要单独给出。不能用我写的那个range（1，1400+），
temp = imagepath+str(imagename)+".jpg"
 image = cv2.imread(temp) # 读取图片  这两行代码你需要给出全路径读你的照片。 谢谢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: gudaost <notifications@github.com&gt;
发送时间: 2020年6月19日 16:17
抄送: MGMCN <gaoshancq@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[MGMCN/Python3-dlib-] 运行结果不成功 (#1)

**Comment by gudaost** [comment]
实在是很有难度，对于小白来说……
要是方便，能否麻烦给个通用版的？把一个文件夹里面的图片中不带人脸的移动到另外一个文件夹……
5555，这种要求提出来真是不好意思啊……

**Comment by MGMCN** [comment]
好的，晚上回复你。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: gudaost <notifications@github.com&gt;
发送时间: 2020年6月19日 16:32
抄送: MGMCN <gaoshancq@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[MGMCN/Python3-dlib-] 运行结果不成功 (#1)

**Comment by gudaost** [comment]
周末又折腾了一通
目前修改的部分：
`# 待检测的图片路径
imagepath = 'D:\\移动不含人脸图片\\test in'
# 训练好的数据集模型
model_path = "D:\\移动不含人脸图片\\shape_predictor_68_face_landmarks.dat"
# 移动到另一个文件夹的路径
moving_path = "D:\\移动不含人脸图片\\test out"`

第二部分修改
`def READimg():
    global  imagepath,index,suofanghou
    print(index)
    print(str(imagename))
    temp = imagepath+str(imagename)+".jpg"
    image = cv2.imread(temp) # 读取图片
    if image is not None:
        suofanghou = cv2.resize(image, None, fx=0.5, fy=0.5, interpolation=cv2.INTER_CUBIC) #缩放图片
        gray = cv2.cvtColor(suofanghou, cv2.COLOR_BGR2GRAY)  # 转灰度图
        detect(gray)`

最末尾的部分
`# if __name__ == '__main__':
init_dir()
load_models()
#      for index in range(1,1404):
READimg()
    # index = 46
    # READimg()`

目前的提示是：
D:\移动不含人脸图片>py 1.py
Traceback (most recent call last):
  File "1.py", line 66, in <module>
    load_models()
  File "1.py", line 22, in load_models
    predictor = dlib.shape_predictor(
RuntimeError: Unable to open D:\移动不含人脸图片\shape_predictor_68_face_landmarks.dat

这是啥情况？另外，有空帮忙提供一个通用版的？

**Comment by MGMCN** [comment]
import cv2
import dlib
import os,shutil

model_path = '/Users/gs/Downloads/shape_predictor_68_face_landmarks.dat'

# movingpath = 'xxxxx/temp.jpg'

face_cascade = dlib.get_frontal_face_detector()
predictor = dlib.shape_predictor(
    model_path
)

imagedirpath = '' # imagedirpath = '/Users/gs/photos'

imagepath = ''    # imagepath = imagedirpath+'/name*.jpg' = '/Users/gs/photos/name*.jpg'

def read_and_detect():
    image = cv2.imread(imagepath)
    if image is not None:
        gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)  # 转灰度图
        # gray = cv2.resize(gray, None, fx=0.5, fy=0.5, interpolation=cv2.INTER_CUBIC)
        faces = face_cascade(gray, 1)
        # print(faces)
        # if len(faces) != 0 : #检测到人脸移动到某个文件夹，并命名为temp.jpg
        #     shutil.move(imagepath,movingpath)
        for face in faces:
        # 在图片中标注人脸，并显示q
            left = face.left()
            top = face.top()
            right = face.right()
            bottom = face.bottom()
            cv2.rectangle(gray, (left, top), (right, bottom), (0, 255, 0), 2)
            cv2.imshow("image", gray)
        while (cv2.waitKey(1) != ord('q')):
            print('.')

if __name__ == '__main__':
    # os.chdir(imagedirpath) # 切换进入存放image的文件夹目录下

    
    imagepath = 'xxxxxxx/xxxxx/xxx.jpg'    # 你只需要用for循环这三行代码，每次修改imagepath和movingpath然后调用
    # movingpath = 'xxxxxxx/xxxxx/xxx.jpg' # read_and_detect()即可
    read_and_detect()



#你自己对照改下，你先试试你一张图片检测，检测成功了，你加个for循环反复检测就可以了。

**Comment by MGMCN** [comment]
这上面一整块都是代码，你自行粘贴了修改路径运行下测试单个图试试，你文件读不出来，你看看是不是中文路径原因，还有你搜搜windows读取路径的格式，我的电脑系统和你不一样。

**Comment by gudaost** [comment]
路径用了非中文，D:\1\1.py
运行方式：CMD管理员模式，D:\1>python 1.py
代码中定义了imagename= os.listdir(imagepath)
for face in faces: # 可以单个运行看看效果的整个部分全部取消了备注井号，即：
    for face in faces: # 可以单个运行看看效果
        # 在图片中标注人脸，并显示
       left = face.left()
       top = face.top()
       right = face.right()
       bottom = face.bottom()
       cv2.rectangle(suofanghou, (left, top), (right, bottom), (0, 255, 0), 2)
       cv2.imshow("image", suofanghou)
    cv2.imshow("Find Faces!", suofanghou) #方便停下来等待查看
    while (cv2.waitKey(1) != ord('q')):
        print('.')

运行结果：
D:\1>python 1.py
['withface.jpg']
然后，没有图片出现，什么都没出现
另外，至少在等待期间，应该显示...一类的吧？这个也没出现

**Comment by MGMCN** [comment]
1、首先你需要检查你这个图片是否成功读取了。2、其次你要知道这个人脸检测的模型不是一定百分百的成功。针对70%的正面人脸是能检测成功的。
我自己的图片使用这个代码是成功检测了的。建议如果你图片太大的话缩小一点检测。谢谢

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: gudaost <notifications@github.com&gt;
发送时间: 2020年6月24日 11:39
抄送: MGMCN <gaoshancq@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[MGMCN/Python3-dlib-] 运行结果不成功 (#1)

**Comment by gudaost** [comment]
经过一番折腾，暂时算是可以运行了，非常感谢您提供的代码和支持！修改后的如下：

`
目前存在的问题：
# 输入文件夹及文档，必须不能是中文
# 无法遍历多级文件
# 输出文件夹必须已经建立，无法自动建立
# 可考虑：计算文档数量（图片文档数量），显示完成百分比或 第几个/总数：文件名

import cv2
import os
import shutil
import dlib

# 设定 path 为运行路径
path = os.getcwd()
# 训练好的数据集模型，路径不可含中文字符。Windows下绝对路径使用“\\”，目前设定为与py文件同目录
model_path = os.path.join(path+'\\shape_predictor_68_face_landmarks.dat')
# 加载的模型变量
face_cascade = None
predictor = None
# 缩放图
suofanghou = None



#######路径修改#######
# 待检测的图片路径，末尾务必有“\\”，可与py文档不同盘符，但路径和图片文件不能有中文(opencv不支持中文)
# 仅遍历该目录下所有文件，不含子文件夹内文档。若出现非图片，则对此文档无操作。目前测试jpg,png文档可正常识别，bmp未成功
imagepath = 'X:\\Program Files\\Pic_Follow_NoFace\\test in\\'

# 移动到另一个文件夹的路径，末尾务必有“\\”
# 目标文件夹可包含中文，可与输入文件夹不同盘符
moving_path = "X:\\Program Files\\Pic_Follow_NoFace\\test out\\"



def load_models():
    global face_cascade,predictor
    face_cascade = dlib.get_frontal_face_detector()
    predictor = dlib.shape_predictor(
        model_path
    )

def READimg():
    global  imagepath,index,suofanghou
    print(str(imagename.name)) #修改
    temp = imagepath+str(imagename.name)# +".jpg"  无需增加扩展名，已包含
    image = cv2.imread(temp) # 读取图片    
    if image is not None:
        suofanghou = cv2.resize(image, None, fx=0.5, fy=0.5, interpolation=cv2.INTER_CUBIC) #缩放图片
        gray = cv2.cvtColor(suofanghou, cv2.COLOR_BGR2GRAY)  # 转灰度图
        detect(gray)
        

def detect(img):
    global face_cascade
    # 探测图中的人脸
    faces = face_cascade(img,3)

    # for face in faces: # 可以单个运行看看效果
    #     # 在图片中标注人脸，并显示
    #    left = face.left()
    #    top = face.top()
    #    right = face.right()
    #    bottom = face.bottom()
    #    cv2.rectangle(suofanghou, (left, top), (right, bottom), (0, 255, 0), 2)
    #    cv2.imshow("image", suofanghou)
    #    cv2.imshow("Find Faces!", suofanghou) #方便停下来等待查看
    #    while (cv2.waitKey(1) != ord('q')):
    #        print('.')

    if len(faces)==0: # 如果没检测到人脸，则将该图移动到另一个文件夹
        move()
    #   print(len(faces))

def init_dir():
    os.chdir(imagepath)

def move():
    shutil.move(imagepath+str(imagename.name),moving_path) #修改参数名称、删除+".jpg"
    print("已移动:" , str(imagename.name))
    
# if __name__ == '__main__':
init_dir()
with os.scandir(imagepath) as entries:# 遍历文件夹内所有文件（不含子文件夹内文件）
    for imagename in entries:
        load_models()
        READimg()

`

**Comment by gudaost** [comment]
另外，咨询个问题，opencv不支持路径及文档中文，这个应该怎么解决？在网上搜索了半天多，一共找到了2个方法，但都没成功。py用的3.8

**Comment by MGMCN** [comment]
推荐你看下这个回答 -> https://www.zhihu.com/question/67157462 ，我使用的python版本是3.6。谢谢
